### PR TITLE
Fix for Cluster Spot Instances: Don't remove azure_attributes on RemoveClusterMeta

### PR DESCRIPTION
**Pull request by dsu4rez**
RemoveClusterMeta is used on New-DatabricksCluster function.

With the previous code, any Cluster re-deployment ("edit" mode) of an existing cluster is leaving the azure_attributes empty, resulting on values by default, thus disabling Spot Instances option if they were set before...

image

It was bug very hard to find :S

### CODE REVIEW

**Comment by dsu4rez** [comment]
@simondmorias Tests passed as well! 
image

**Comment by simondmorias** [comment]
Many thanks @dsu4rez - the preview version will release shortly. I will push a public version later this week.

**Comment by dsu4rez** [comment]
Hi @simondmorias, when the Public release is planned to happen?
thanks!

Btw, there is a branch in this repo with my name on it (a mistake of a few months ago), could you remove it?
image

**Comment by simondmorias** [comment]
Sorted (sorry I had another change to get in). v 2.2.5299 includes this.

**Pull request merged**
