### PR TITLE
Script for adding notebook job to Databricks

### PR DESCRIPTION
**Pull request by tadziqusky**
I created Powershell script that uses Databricks API 2.0 to create a Notebook Job based on provided parameters.

### CODE REVIEW

**Comment by simondmorias** [comment]
Thanks for this. I’m on vacation for two weeks so will look when I get back.

**Comment by tadziqusky** [comment]
Hi,
any update on this? It would be great if you could have a look on this code, I would like to use it from  azure.databricks.cicd.tools package. 
Thanks.

**Comment by simondmorias** [comment]
Hoping to do this afternoon (worst case Thursday). I was wanting to align a bunch of things first. I will accept the PR but I'm going to rename to Add-DatabricksNotebookJob.
I am also extend later on to prevent it creating duplicate jobs.
Thanks

**Comment by tadziqusky** [comment]
Great! Please take your time to adjust the script as you think it would be the best, it's not so urgent for me, altought in upcoming weeks I would like to be able to use it.
Thanks.

**Pull request merged**
