### PR TITLE
Change from PS cmdlets to .NET commands for handling new lines and files

### PR DESCRIPTION
**Pull request by RichieBzzzt**
PowerShell cmdlets have proven to cause issues across versions of PS and different OS and Git configs. Replace with .NET cmds seems to have removed issues of line formatting. 

Have also removed the error where empty notebooks causes the threadjob to fail by checking ```NewResponse``` is not null.

Have got the error message writing to console when one of the threadjobs have failed, which wasn't the case before.

Have updated the ```Export-DatabricksFolder.tests.ps1``` to write the output to where the notebooks were initially pushed from so that we can check if the content has been altered by any of the import/export commands.

Added more notebooks with more lines for testing.
Should resolve - 
#138 

#140 

Should undo damage caused by - 

#139

### CODE REVIEW

**Comment by RichieBzzzt** [comment]
I've got a couple more changes coming that should fix #150 I am running tests now!

**Comment by RichieBzzzt** [comment]
OK written tests around handling 429 and 404 web errors. It's good to go, pending review etc.

**Comment by ryanbbrownavanade** [comment]
Confused as to how this fixes the 429 error I raised earlier...what changes have been made to the sleep timing?

**Comment by RichieBzzzt** [comment]
> Confused as to how this fixes the 429 error I raised earlier...what changes have been made to the sleep timing?

This check in should resolve it - https://github.com/DataThirstLtd/azure.databricks.cicd.tools/pull/151/commits/bd0eeb448a6cfcfb01574ff3228acaffbaf855e2

added a retry  if first attempt fails - https://github.com/DataThirstLtd/azure.databricks.cicd.tools/pull/151/commits/74b27d6de0c72fc1af6ee6696be6f2a48c79d3dc

Admittedly the changes are lost in the check-ins and not properly commented.

**Comment by ryanbbrownavanade** [comment]
@RichieBzzzt reviewed the commits and see the parameterization as needed. I will now attempt to refactor my code to use it. Thank you for your prompt attention to this.

**Pull request merged**
