### PR TITLE
Secretformatting

### PR DESCRIPTION
**Pull request by RichieBzzzt**
Been having issues with passing json content as secrets; using hashtable then convertto-json seems to have fixed it. Have added tests for other secret types that may be stored.

### CODE REVIEW

**Comment by RichieBzzzt** [comment]
@simondmorias Can you review and approve please?

**Comment by RichieBzzzt** [comment]
Cheers, we've got loads of secrets that are json and we're trying to deploy them.

**Comment by simondmorias** [comment]
The new tests are failing, but I'm going to let in through and publish as preview. I suspect the issue is something else.

**Comment by simondmorias** [comment]
@RichieBzzzt PowerShell Gallery is down so can't publish - will try again later

**Comment by RichieBzzzt** [comment]
OK thanks. Yes we have been having fun with PSGallery today as well.

**Pull request merged**
