### PR TITLE
Fixing broken clean switch on Import-DatabricksFolder

### LINKED ISSUE #127: Clean workspace switch not working
**Issue description**
When Import-DatabricksFolder is invoked with the clean switch it should delete the specified Databricks workspace folder and all files within it before copying new files. However, it does not work as documented.

**Steps to reproduce**
1. Create a deployment pipeline in Azure DevOps. Ensure that the "Clean" checkbox is ticked.
1. Manually create a notebook or folder in that workspace in Databricks 
1. Run the deployment from Azure DevOps

**Expected result**
Only the new files deployed are avaiable in the Databricks workspace

**Actual result**
The manually created file is still in the workspace 

**Additional information**
I believe this issue was introduced by placing the Get-DatabricksWorkspaceFolder call inside the Trap statement in [https://github.com/DataThirstLtd/azure.databricks.cicd.tools/pull/114/files](https://github.com/DataThirstLtd/azure.databricks.cicd.tools/pull/114/files). This change appears to have been added to ensure that the clean switch handles the scenario where there is no workspace to clean and the Databricks API returns a 404 error, but accidentally placing this inside the trap means it is actually never called and files and folders are never cleaned from an existing workspace.

### PR DESCRIPTION
**Pull request by simondmorias**
Fixes #127 
A couple of the test broke - I think because they may not run in order. Just cleaned up slightly

### CODE REVIEW

**Comment by rafaelpierre** [comment]
Not sure if related, but starting this morning I'm getting Error 400 when I try to deploy my Notebooks. At first thought could be related to some issue with the notebook code (e.g. encoding etc), but then I re-deployed yesterday's release (which worked), and I'm getting the same error.

My code is hosted on Github.

image

**Comment by simondmorias** [comment]
There was a code deployment yesterday which must be causing this. Though my test deployment is working. Give me a couple of hours. The change was on the clean flag. For now removing it may help.

________________________________

**Comment by simondmorias** [comment]
I have rolled back the release for now so that I can look into this in more detail later.
In the meantime @rafaelpierre (firstly thanks for reporting), could you:
- Let us know if the rollback has resolved the issue (you should see version 0.9.2839 in the logs)
- Confirm what soft of files you were deploying (just notebooks)?
- Is there any thing in the target Databricks folder already?
- Is there anything interesting about the paths you are using - special characters etc.
Thanks

**Comment by rafaelpierre** [comment]
Hey @simondmorias,

Still haven't tested again with the previous version, will let you know once I do. 

Files that I tried to deploy were just .py files.

There was already a folder in the Databricks workspace when I deployed (same scenario as previous deployments prior to yesterday, when it still worked).

No special characters in the paths

**Comment by jamesryanuk** [comment]
Hi @rafaelpierre,

If you do still see a problem when re-testing this, please could you add a variable called system.debug to your release pipeline and set its value to true? This should enable detailed logging and may help identify the issue. Please let us know how you get on, as the latest release contained a fix for a bug that was impacting us, and I'm keen to see it resolved in the published version of this plugin as soon as possible. Thanks!

**Comment by simondmorias** [comment]
Sorry for the delay. I'm unable to reproduce the error and am releasing this again. Please raise a new issue if this continues.

**Pull request merged**
